name: Manual trigger

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Who to greet"
        default: "World"

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Hello Step
        run: echo "Hello ${{ github.event.inputs.name }}"
      - name: User Name
        run: echo "User Name ${GITHUB_ACTOR}"
      - name: User ID
        run: echo "User ID ${GITHUB_ACTOR_ID}"
        
